sudo: required
dist: trusty
services:
- docker
install:
- docker build -t test meta
script:
- docker run -ti test /bin/true
- docker run -ti test /bin/bash --version
- docker run -ti test gem which dock0
- docker run -ti test ls /opt/run
notifications:
  email: false
  slack:
    secure: MBg7BccKUzUJvFacgG+XkZPWlorSQrgogfz6QX5gsltVzDzgAkZYrI3UjOKHpUnL8GeMEf6O0g70IUq82Zue+f5hq72erbBC/EFY+dv9qgJ0JI0TwC/kU615jZexVKKz7tRO/Oj6xYF62nIpYEP38Y8zRqynLYXyd89JflP1aFsxueja+dtsjQCtIVRxcEr+XerEC5jXyHQc4+QZGVzBiAVu2jyODflDDsqFwVgHHiToluZ1VN+Ge1FUV/s7ukXZ7fZHiQh0qB64T/GRcB970aY4PWLMMEvlS3JNUsxEX2bdhcfXXZMOnmYpigBxLcYQ7iEXeWeCSUMyMvGLidiMudCOr5Qfpd0P88Dxks+/oertBfIHRHC+D9hs9NhNA1c4ztFv7oVNIOlFylSA0s47CtRZQnVcXsvDPcV5P8DS1979KRhIicQvpl5sdDmQeQJ88qDFcW6tTcUC32E9o3nEC0Sd7YcpeOhU/CffIOvAWABG++kkFWhgJJ5ybO/XuMOJn87EU0qtU295LLX2axAmQhJpAjCARAqktmFSc7kavfiv0+ko0Scw5sEv61ttby5z/RiY9TK+VQx54jcuOUNLUYmSB++/ME/wbcnHjM5FqFbD0oFZRV4NhWgyBITCNqVXO063fXDWJ99UAIiW9iuSc5SUdIc69YKLceXK5xm64o0=
