paths:
  templates: ./templates
  scripts: ./scripts
  build: /run/dock0/bootmnt
  base: /
org: dock0
artifacts:
  - name: kernel
    version: 3.18_1
    file: vmlinuz
  - name: vm_root
    version: 0.0.21
    file: root.fs.sfs
  - name: initrd
    version: 0.0.22
    file: initrd.img
