---
paths:
  templates: "./templates"
  scripts: "./scripts"
  build: "/run/vm/bootmnt"
  base: "/"
org: dock0
artifacts:
- name: kernel
  version: 4.1-rc3_5
  file: vmlinuz
- name: vm_root
  version: 0.0.100
  file: root.fs.sfs
- name: initrd
  version: 0.0.45
  file: initrd.img
