paths:
  templates: ./templates
  scripts: ./scripts
  build: /run/dock0/bootmnt
  base: /
org: dock0
artifacts:
  - name: kernels
    version: 3.18_1
    file: vmlinuz
    link: /current/kernel
  - name: vm_root
    version: 0.0.15
    file: root.fs.sfs
    link: /current/vm_root
  - name: initrd
    version: 0.0.15
    file: initrd.img
    link: /current/initrd
