---
paths:
  templates: "./templates"
  scripts: "./scripts"
  build: "/run/vm/bootmnt"
  base: "/"
org: dock0
artifacts:
- name: kernel
  version: 4.0-rc1_3
  file: vmlinuz
- name: vm_root
  version: 0.0.82
  file: root.fs.sfs
- name: initrd
  version: 0.0.36
  file: initrd.img
