---
paths:
  templates: "./templates"
  scripts: "./scripts"
  build: "/run/vm/bootmnt"
  base: "/"
org: dock0
artifacts:
- name: kernel
  version: 4.5-rc4_1
  file: vmlinuz
- name: rootfs
  version: 0.0.180
  file: root.fs.sfs
- name: initrd
  version: 0.0.66
  file: initrd.img
