---
paths:
  templates: "./templates"
  scripts: "./scripts"
  build: "/run/vm/bootmnt"
  base: "/"
org: dock0
artifacts:
- name: kernel
  version: 4.3-rc2_2
  file: vmlinuz
- name: vm_root
  version: 0.0.132
  file: root.fs.sfs
- name: initrd
  version: 0.0.55
  file: initrd.img
