---
paths:
  templates: "./templates"
  scripts: "./scripts"
  build: "/run/vm/bootmnt"
  base: "/"
org: dock0
artifacts:
- name: kernel
  version: 4.2-rc4_1
  file: vmlinuz
- name: vm_root
  version: 0.0.106
  file: root.fs.sfs
- name: initrd
  version: 0.0.52
  file: initrd.img
