paths:
  templates: ./templates
  scripts: ./scripts
  build: /run/vm/bootmnt
  base: /
org: dock0
artifacts:
  - name: kernel
    version: 3.19-rc1_2
    file: vmlinuz
  - name: vm_root
    version: 0.0.62
    file: root.fs.sfs
  - name: initrd
    version: 0.0.33
    file: initrd.img
