---
paths:
  templates: "./templates"
  scripts: "./scripts"
  build: "/run/vm/bootmnt"
  base: "/"
org: dock0
artifacts:
- name: kernel
  version: 4.18-rc7-1
  file: vmlinuz
- name: rootfs
  version: 0.0.200
  file: root.fs.sfs
- name: initrd
  version: 0.1.0
  file: initrd.img
