paths:
  templates: ./templates
  scripts: ./scripts
  build: /run/dock0/bootmnt
  base: /
org: dock0
artifacts:
  - name: kernel
    version: 3.19-rc1_2
    file: vmlinuz
  - name: vm_root
    version: 0.0.60
    file: root.fs.sfs
  - name: initrd
    version: 0.0.32
    file: initrd.img
